=== Krot2bic/PyTFall/game/schema/items.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "properties": {
    "add_be_spells": {
      "items": { "type": "string" },
      "type": "array"
    },
    "addeffects": {
      "items": { "type": "string" },
      "type": "array"
    },
    "addtraits": {
      "items": { "type": "string" },
      "type": "array"
    },
    "attacks": {
      "items": { "type": "string" },
      "type": "array"
    },
    "badness": { "type": "number" },
    "badtraits": { "type": "array" },
    "cblock": { "type": "number" },
    "ceffect": { "type": "string" },
    "ch_multiplier": { "type": "number" },
    "chance": { "type": "number" },
    "ctemp": { "type": "number" },
    "damage_multiplier": { "type": "number" },
    "defence_bonus": {
      "additionalProperties": false,
      "properties": {
        "magic": { "type": "number" },
        "melee": { "type": "number" },
        "ranged": { "type": "number" }
      },
      "type": "object"
    },
    "defence_multiplier": {
      "additionalProperties": false,
      "properties": {
        "magic": { "type": "number" },
        "melee": { "type": "number" },
        "ranged": { "type": "number" },
        "status": { "type": "number" }
      },
      "type": "object"
    },
    "delivery_bonus": {
      "additionalProperties": false,
      "properties": {
        "magic": { "type": "number" },
        "status": { "type": "number" }
      },
      "type": "object"
    },
    "delivery_multiplier": {
      "additionalProperties": false,
      "properties": {
        "magic": { "type": "number" },
        "melee": { "type": "number" },
        "ranged": { "type": "number" },
        "status": { "type": "number" }
      },
      "type": "object"
    },
    "desc": { "type": "string" },
    "dismod": { "type": "number" },
    "eqchance": { "type": "number" },
    "evasion_bonus": { "type": "number" },
    "goodrait": {
      "items": { "type": "string" },
      "type": "array"
    },
    "goodtraits": { "type": "array" },
    "hidden": { "type": "boolean" },
    "icon": { "type": "string" },
    "id": { "type": "string" },
    "infinite": { "type": "boolean" },
    "jump_to_label": { "type": "string" },
    "locations": {
      "items": { "type": "string" },
      "type": "array"
    },
    "max": {
      "additionalProperties": false,
      "properties": {
        "agility": { "type": "number" },
        "attack": { "type": "number" },
        "character": { "type": "number" },
        "charisma": { "type": "number" },
        "constitution": { "type": "number" },
        "defence": { "type": "number" },
        "health": { "type": "number" },
        "intelligence": { "type": "number" },
        "joy": { "type": "number" },
        "luck": { "type": "number" },
        "magic": { "type": "number" },
        "mp": { "type": "number" },
        "refinement": { "type": "number" },
        "vitality": { "type": "number" }
      },
      "type": "object"
    },
    "mdestruct": { "type": "boolean" },
    "min": {
      "additionalProperties": false,
      "properties": {
        "attack": { "type": "number" },
        "character": { "type": "number" },
        "joy": { "type": "number" },
        "mp": { "type": "number" }
      },
      "type": "object"
    },
    "mod": {
      "additionalProperties": false,
      "properties": {
        "agility": { "type": "number" },
        "attack": { "type": "number" },
        "character": { "type": "number" },
        "charisma": { "type": "number" },
        "constitution": { "type": "number" },
        "defence": { "type": "number" },
        "disposition": { "type": "number" },
        "exp": { "type": "number" },
        "gold": { "type": "number" },
        "health": { "type": "number" },
        "intelligence": { "type": "number" },
        "joy": { "type": "number" },
        "luck": { "type": "number" },
        "magic": { "type": "number" },
        "mp": { "type": "number" },
        "refinement": { "type": "number" },
        "service": { "type": "number" },
        "vitality": { "type": "number" }
      },
      "type": "object"
    },
    "mod_skills": {
      "additionalProperties": false,
      "properties": {
        "anal": {
          "items": { "type": "number" },
          "type": "array"
        },
        "bartending": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        },
        "bdsm": {
          "items": { "type": "number" },
          "type": "array"
        },
        "cleaning": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        },
        "dancing": {
          "items": { "type": "number" },
          "type": "array"
        },
        "exploration": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        },
        "fishing": {
          "items": { "type": "number" },
          "type": "array"
        },
        "group": {
          "items": { "type": "number" },
          "type": "array"
        },
        "management": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        },
        "oral": {
          "items": { "type": "number" },
          "type": "array"
        },
        "refinement": {
          "items": { "type": "number" },
          "type": "array"
        },
        "service": {
          "items": { "type": "number" },
          "type": "array"
        },
        "sex": {
          "items": { "type": "number" },
          "type": "array"
        },
        "strip": {
          "items": { "type": "number" },
          "type": "array"
        },
        "swimming": {
          "items": { "type": "number" },
          "type": "array"
        },
        "teaching": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        },
        "vaginal": {
          "items": { "type": "number" },
          "type": "array"
        },
        "waiting": {
          "items": [
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" },
            { "type": "number" }
          ],
          "type": "array"
        }
      },
      "type": "object"
    },
    "mreusable": { "type": "boolean" },
    "mtemp": { "type": "number" },
    "price": { "type": "number" },
    "removeeffects": {
      "items": { "type": "string" },
      "type": "array"
    },
    "removetraits": { "type": "array" },
    "sex": { "type": "string" },
    "skillmax": { "type": "number" },
    "slot": { "type": "string" },
    "statmax": { "type": "number" },
    "type": { "type": "string" }
  },
  "required": [
    "chance",
    "icon",
    "id",
    "price",
    "slot",
    "desc"
  ],
  "type": "object"
}

=== Krot2bic/PyTFall/game/content/db/items_building_resources.json
[
    {
    "id": "Bricks",
    "desc": "High quality resource for your building upgrades!",
    "icon": "content/items/building_resources/bricks.png",
    "price": 25,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    },
    {
    "id": "Glass",
    "desc": "High quality resource for your building upgrades!",
    "icon": "content/items/building_resources/glass.png",
    "price": 45,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    },
    {
    "id": "Wood",
    "desc": "High quality resource for your building upgrades!",
    "icon": "content/items/building_resources/wood.png",
    "price": 25,
    "sex": "unisex",
    "chance": 100,
    "badness": 100,
    "eqchance": 0,
    "hidden": false,
    "infinite": true,
    "slot": "resources",
    "type": "building",
    "locations": ["Work Shop", "Look around"]
    }
]

=== Krot2bic/PyTFall/game/content/db/items_loot.json
[
    {
    "id": "Old Coins",
    "desc": "A handful of coins. Coinage is weird, but gold is gold.",
    "icon": "content/items/loot/coins.png",
    "price": 50,
    "chance": 90,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration", "Look around", "Fishing"]
    },
    {
    "id": "Old Purse",
    "desc": "A purse of coins. Coinage is weird, but gold is gold.",
    "icon": "content/items/loot/purse.png",
    "price": 100,
    "chance": 80,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Old Bag",
    "desc": "A bag of coins. Coinage is weird, but gold is gold.",
    "icon": "content/items/loot/bag.png",
    "price": 150,
    "chance": 70,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Old Chest",
    "desc": "A chest of coins. Coinage is weird, but gold is gold.",
    "icon": "content/items/loot/chest.png",
    "price": 200,
    "chance": 60,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Amethyst",
    "desc": "A purple variety of quartz suitable for use in jewelry.",
    "icon": "content/items/loot/amethyst.png",
    "price": 300,
    "chance": 50,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Topaz",
    "desc": "A yellow silicate mineral. It's colorless and transparent in pure form but usually tinted by impurities.",
    "icon": "content/items/loot/topaz.png",
    "price": 400,
    "chance": 45,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Apatite",
    "desc": "Infrequently used as a gemstone, apatites are still quite valuable.",
    "icon": "content/items/loot/apatite.png",
    "price": 500,
    "chance": 40,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Sapphire",
    "desc": "A commonly used in jewelry deep blue gemstone.",
    "icon": "content/items/loot/sapphire.png",
    "price": 600,
    "chance": 35,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Emerald",
    "desc": "A fragile green gemstone.",
    "icon": "content/items/loot/emerald.png",
    "price": 700,
    "chance": 30,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Ruby",
    "desc": "A very hard and beautiful red gemstone.",
    "icon": "content/items/loot/ruby.png",
    "price": 800,
    "chance": 25,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Diamond",
    "desc": "A one of the best-known and most sought-after gemstones with uperlative physical qualities.",
    "icon": "content/items/loot/diamond.png",
    "price": 1000,
    "chance": 20,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Gold Ingots",
    "desc": "Gold bars of high purity.",
    "icon": "content/items/loot/gold.png",
    "price": 3000,
    "chance": 5,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Golden Mask",
    "desc": "A ceremonial golden mask remained from ancient civilisations.",
    "icon": "content/items/loot/gm.png",
    "price": 250,
    "chance": 75,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Golden Statue",
    "desc": "A ceremonial golden statue remained from ancient civilisations.",
    "icon": "content/items/loot/gs.png",
    "price": 250,
    "chance": 48,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Golden Piranha",
    "desc": "A golden statue of extinct predatory fish remained from ancient civilisations.",
    "icon": "content/items/loot/gs.png",
    "price": 200,
    "chance": 30,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Fishing"]
    },
    {
    "id": "Golden God",
    "desc": "A golden statue of the god of the hunt remained from ancient civilisations.",
    "icon": "content/items/loot/gg.png",
    "price": 1500,
    "chance": 15,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Exploration"]
    },
    {
    "id": "Green Pearl",
    "desc": "A valuable object produced by living shelled molluscs.",
    "icon": "content/items/loot/green_pearl.png",
    "price": 200,
    "chance": 15,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Diving"]
    },
    {
    "id": "Pink Pearl",
    "desc": "A valuable object produced by living shelled molluscs.",
    "icon": "content/items/loot/pink_pearl.png",
    "price": 150,
    "chance": 20,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Diving"]
    },
    {
    "id": "Blue Pearl",
    "desc": "A valuable object produced by living shelled molluscs.",
    "icon": "content/items/loot/blue_pearl.png",
    "price": 100,
    "chance": 25,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Diving"]
    },
    {
    "id": "Black Pearl",
    "desc": "A valuable object produced by living shelled molluscs.",
    "icon": "content/items/loot/black_pearl.png",
    "price": 250,
    "chance": 10,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Diving"]
    },
    {
    "id": "Pearl",
    "desc": "A valuable object produced by living shelled molluscs.",
    "icon": "content/items/loot/pearl.png",
    "price": 50,
    "chance": 30,
    "slot": "loot",
    "type": "treasure",
    "locations": ["Diving"]
    }
  ]
