=== Krot2bic/PyTFall/game/schema/misc.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "properties": {
    "boss": { "type": "string" },
    "boss_name": { "type": "string" },
    "desc": { "type": "string" },
    "fame": {
      "items": { "type": "number" },
      "type": "array"
    },
    "id": { "type": "string" },
    "items": {
      "additionalProperties": false,
      "properties": {
        "Angelic Blade": { "type": "number" },
        "Angelic Bow": { "type": "number" },
        "Antidote": { "type": "number" },
        "Archmage Staff": { "type": "number" },
        "Armor of the Battlemaiden": { "type": "number" },
        "Aromatic Dust": { "type": "number" },
        "Aromatic Pendant": { "type": "number" },
        "Artisan Outfit": { "type": "number" },
        "Assassin Dagger": { "type": "number" },
        "Balanced Claws": { "type": "number" },
        "Battle Cape": { "type": "number" },
        "Bestial Ring": { "type": "number" },
        "Bimbo Ring": { "type": "number" },
        "Boots of Mercury": { "type": "number" },
        "Bracer of Seduction": { "type": "number" },
        "Bracer of Toughness": { "type": "number" },
        "Bullwhip": { "type": "number" },
        "Casual Clothes": { "type": "number" },
        "Cat O'Nine Tails": { "type": "number" },
        "Ceremonial Sabre": { "type": "number" },
        "Chain Scythe": { "type": "number" },
        "Chainmail Bikini": { "type": "number" },
        "Cloak of Invisibility": { "type": "number" },
        "Demonic Blade": { "type": "number" },
        "Demonic Bow": { "type": "number" },
        "Demonic Cloak": { "type": "number" },
        "Devil Arms": { "type": "number" },
        "Draconic Leather Armor": { "type": "number" },
        "Draconic Leather Boots": { "type": "number" },
        "Draconic Leather Gloves": { "type": "number" },
        "Elven Armor": { "type": "number" },
        "Elven Boots": { "type": "number" },
        "Elven Bow": { "type": "number" },
        "Elven Cape": { "type": "number" },
        "Elven Gloves": { "type": "number" },
        "Elven Ranger Armbands": { "type": "number" },
        "Elven Ranger Armor": { "type": "number" },
        "Elven Ranger Boots": { "type": "number" },
        "Elven Rapier": { "type": "number" },
        "Elven Sage Armbands": { "type": "number" },
        "Elven Sage Armor": { "type": "number" },
        "Elven Sage Boots": { "type": "number" },
        "Enchanted Dagger": { "type": "number" },
        "Enlarger": { "type": "number" },
        "Excalibur": { "type": "number" },
        "Faerie Boots": { "type": "number" },
        "Faerie Bracers": { "type": "number" },
        "Faerie Cloak": { "type": "number" },
        "Faerie Gown": { "type": "number" },
        "Foldable Crossbow": { "type": "number" },
        "Garem Charm": { "type": "number" },
        "Glass Shoes": { "type": "number" },
        "Gloves of Concentration": { "type": "number" },
        "Gloves of Swordplay": { "type": "number" },
        "Godward Shell": { "type": "number" },
        "Good Luck Charm": { "type": "number" },
        "Great Healing Potion": { "type": "number" },
        "Great Mana Potion": { "type": "number" },
        "Great Potion of Serenity": { "type": "number" },
        "Healing Mist": { "type": "number" },
        "Healing Potion": { "type": "number" },
        "Health Charm": { "type": "number" },
        "Jeweled Poignard": { "type": "number" },
        "Kunai": { "type": "number" },
        "Kung Fu Shoes": { "type": "number" },
        "Kunoichi Outfit": { "type": "number" },
        "Kunoichi Suit": { "type": "number" },
        "Leash": { "type": "number" },
        "Mage Mantle": { "type": "number" },
        "Mage Robe": { "type": "number" },
        "Magic Bow": { "type": "number" },
        "Magician Handbag": { "type": "number" },
        "Mail Armor": { "type": "number" },
        "Mail Boots": { "type": "number" },
        "Mail Gloves": { "type": "number" },
        "Mana Charm": { "type": "number" },
        "Mana Potion": { "type": "number" },
        "Mana Powder": { "type": "number" },
        "Mantle of the Keeper": { "type": "number" },
        "Mantle of the Priest": { "type": "number" },
        "Mercenary Clothes": { "type": "number" },
        "Minor Reflector": { "type": "number" },
        "Minor Ring of Physique": { "type": "number" },
        "Minor Ring of the Horndog": { "type": "number" },
        "Mistress Boots": { "type": "number" },
        "Mithril Armor": { "type": "number" },
        "Mithril Boots": { "type": "number" },
        "Mithril Gloves": { "type": "number" },
        "Necklace of Pain Reversal": { "type": "number" },
        "Ninja Boots": { "type": "number" },
        "Ninja Cloak": { "type": "number" },
        "Ninja Gloves": { "type": "number" },
        "Ornate Gladius": { "type": "number" },
        "Pet Collar": { "type": "number" },
        "Potion of Barkskin": { "type": "number" },
        "Potion of Lightning Speed": { "type": "number" },
        "Potion of Serenity": { "type": "number" },
        "Rainbow Ring": { "type": "number" },
        "Reflector": { "type": "number" },
        "Ring of Clear Thought": { "type": "number" },
        "Ring of Health": { "type": "number" },
        "Ring of Luck": { "type": "number" },
        "Ring of Magic Energy": { "type": "number" },
        "Ring of Physique": { "type": "number" },
        "Ring of Pleasure": { "type": "number" },
        "Ring of Protection": { "type": "number" },
        "Ring of Recklessness": { "type": "number" },
        "Ring of the Horndog": { "type": "number" },
        "Rogue's Ring": { "type": "number" },
        "Rune Staff": { "type": "number" },
        "Scythe of Death": { "type": "number" },
        "Short Kimono": { "type": "number" },
        "Shuriken": { "type": "number" },
        "Small Healing Potion": { "type": "number" },
        "Small Mana Potion": { "type": "number" },
        "Small Potion of Serenity": { "type": "number" },
        "Spiked Brass Knuckles": { "type": "number" },
        "Spiked Collar": { "type": "number" },
        "Spirit-Defender": { "type": "number" },
        "Spray with Acid": { "type": "number" },
        "Starlit Robes": { "type": "number" },
        "Succubus'Wardress": { "type": "number" },
        "Throwing Knives": { "type": "number" },
        "Training Suit": { "type": "number" },
        "Ultimate Healing Potion": { "type": "number" },
        "Ultimate Mana Potion": { "type": "number" },
        "Victory Charm": { "type": "number" },
        "Wand of Concentration": { "type": "number" },
        "Witch's Cloak": { "type": "number" },
        "Witch's Ring": { "type": "number" },
        "Wizard Robes": { "type": "number" },
        "Wristbands of Power": { "type": "number" }
      },
      "type": "object"
    },
    "level": { "type": "number" },
    "mobs": {
      "items": { "type": "string" },
      "type": "array"
    },
    "multiplier": {
      "items": { "type": "number" },
      "type": "array"
    },
    "name": { "type": "string" },
    "price": { "type": "number" },
    "reputation": {
      "items": { "type": "number" },
      "type": "array"
    },
    "reward": {
      "additionalProperties": false,
      "properties": {
        "Angel_gear": { "type": "number" },
        "Armor": { "type": "number" },
        "Cons_common": { "type": "number" },
        "Demon_gear": { "type": "number" },
        "Elven_gear": { "type": "number" },
        "Ench_gear": { "type": "number" },
        "Faerie_gear": { "type": "number" },
        "Legendary_gear": { "type": "number" },
        "Mage_gear": { "type": "number" },
        "Male_armor": { "type": "number" },
        "Ninja_gear": { "type": "number" },
        "Sex": { "type": "number" },
        "Weapon": { "type": "number" }
      },
      "type": "object"
    },
    "upkeep": { "type": "number" }
  },
  "type": "object"
}

=== Krot2bic/PyTFall/game/content/db/buildings/adverts.json
[
    {
        "name": "Sign",
        "desc": "Put up a sign above entrance. Sensible advertisement for every brothel that you own. You obviously pay full fee for this only once and then 10% of the fee if you removed the sign for some reason and put it up again.",
        "price": 200,
        "fame": [0, 1]
    },
    {
        "name": "Flyers",
        "desc": "Hire someone to handout flyers in the city. You will pay fee for this service each day",
        "upkeep": 30,
        "fame": [0, 1]
    },
    {
        "name": "Magazine",
        "desc": "Put an advertisement in local 'Playdude' magazine. Target your audience for a modest fee. Will cost you an amount of gold each day",
        "upkeep": 50,
        "fame": [2, 3]
    },
    {
        "name": "Billboard",
        "desc": "Get some pro's to put a large billboard on the road to city. Upkeep and rent will cost you a daily fee",
        "upkeep": 100,
        "fame": [0, 2]
    },
    {
        "name": "Girl",
        "desc": "Hire a pretty girl to attact clients into your buildings. This will cost you 50 once and 150 a day.",
        "price": 50,
        "upkeep": 150,
        "fame": [0, 1],
        "reputation": [0, 2]
    },
    {
        "name": "Celebrity",
        "desc": "Pay a celebrity to come into your building and publicly endorse it! You will pay 5000 once and 1000 a day to keep her.",
        "price": 5000,
        "fame": [50, 100],
        "reputation": [50, 100]
    }
]
