=== Krot2bic/PyTFall/game/schema/new_npcs.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "additionalProperties": false,
  "properties": {
    "ab_traits": { "type": "array" },
    "attack_skills": {
      "items": { "type": "string" },
      "type": "array"
    },
    "base_race": { "type": "string" },
    "basetraits": {
      "items": { "type": "string" },
      "type": "array"
    },
    "blocked_traits": { "type": "array" },
    "color": { "type": "string" },
    "desc": { "type": "string" },
    "fullname": { "type": "string" },
    "gender": { "type": "string" },
    "gold": { "type": "number" },
    "id": { "type": "string" },
    "level": { "type": "number" },
    "location": { "type": "string" },
    "magic_skills": { "type": "array" },
    "name": { "type": "string" },
    "origin": { "type": "string" },
    "race": { "type": "string" },
    "skills": {
      "additionalProperties": false,
      "properties": {
        "cleaning": { "type": "number" },
        "exploration": { "type": "number" },
        "management": { "type": "number" },
        "teaching": { "type": "number" }
      },
      "required": [
        "exploration",
        "management",
        "teaching",
        "cleaning"
      ],
      "type": "object"
    },
    "stats": {
      "additionalProperties": false,
      "properties": {
        "agility": { "type": "number" },
        "attack": { "type": "number" },
        "character": { "type": "number" },
        "charisma": { "type": "number" },
        "constitution": { "type": "number" },
        "defence": { "type": "number" },
        "intelligence": { "type": "number" },
        "luck": { "type": "number" },
        "magic": { "type": "number" }
      },
      "required": [
        "agility",
        "attack",
        "character",
        "charisma",
        "constitution",
        "defence",
        "intelligence",
        "magic",
        "luck"
      ],
      "type": "object"
    },
    "status": { "type": "string" },
    "traits": { "type": "array" },
    "what_color": { "type": "string" }
  },
  "required": [
    "ab_traits",
    "attack_skills",
    "base_race",
    "basetraits",
    "blocked_traits",
    "fullname",
    "gender",
    "gold",
    "id",
    "level",
    "location",
    "magic_skills",
    "name",
    "origin",
    "race",
    "stats",
    "status",
    "traits",
    "desc"
  ],
  "type": "object"
}

=== Krot2bic/PyTFall/game/content/new_npcs/thugs/data_street_thug.json
[
    {
        "id": "street_thug",
        "name": "Thug",
        "fullname": "Street Thug",
        "desc": "Just another city thug looking for easy prey in dark alleys.",
        "origin": "PyTFall",
        
        "base_race": "Human",
        "gender": "male",
        "race": "Human",
        "location": "city",
        "status": "free",
        "gold": 250,
        
        "level": 30,
        "basetraits": ["Warrior"],
        
        "stats": {
            "charisma": 30,
            "constitution": 50,
            "luck": -40,
            "character": 75,
            "intelligence": 15,
            "attack": 40,
            "magic": 5,
            "defence": 55,
            "agility": 70
        },
        "blocked_traits": [
        
        ],
        "ab_traits": [
        
        ],
        
        "traits": [

        ],
        "attack_skills": [
            "Sword Slash"
        ],
        "magic_skills": [

        ]
    }
]
